name: CI
on:
    push:
        branches:
        - master
    pull_request:
        branches:
        - master
jobs:
    flutter_test:
        name: Flutter Test
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: subosito/flutter-action@v1
          with:
              channel: 'stable'
        - run: flutter doctor
        - run: flutter pub get
        - run: flutter test